# Bounds the age field and gives the model a default ordering.
# Generated by Django 5.0.6 on 2024-06-11 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentrecord",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="age",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="course",
            field=models.CharField(
                choices=[
                    ("BS-IT", "BS Information Technology"),
                    ("BS-CS", "BS Computer Science"),
                    ("BS-DS", "BS Data Science"),
                    ("BS-IS", "BS Information Systems"),
                ],
                max_length=50,
            ),
        ),
    ]
